service: ri-quote
provider:
  name: aws
  region: us-east-1
  runtime: provided.al2
  memorySize: 128
  stage: development
plugins:
  - ./vendor/bref/bref
functions:
  movie-get:
    handler: Entrata\ResidentInsureQuote\Handlers\QuoteHandler
    events:
      - httpApi: GET /quote/{data}/{year}
  quote-get:
    handler: Entrata\ResidentInsureQuote\Handlers\QuoteHandler
    events:
      - httpApi: GET /quote/{data}
  quote-post:
    handler: Entrata\ResidentInsureQuote\Handlers\QuoteHandler
    events:
      - httpApi: POST /quote/{data}
package:
  patterns:
    - '!node_modules/**'
    - '!tests/**'